.TH KSC "1" "December 2017" "ksc - Version 0.11.0" "User Commands"
.SH NAME
ksc \- Linux kernel module source checker
.SH SYNOPSIS
.B ksc
[\fB -d | --directory \fR] DIRECTORY
.TP
.B ksc [\fB --ko FILE | -s -p PREVIOUS_REPORT \fR]
.SH OPTIONS
KSC  accepts command-line arguments, and has both a long and short form usage. 
You can use either style or combine them to specify options. When the tool is 
run with kernel module sources it checks for all four architectures, and when 
run with binary kernel modules, it checks for the specific architecture for which 
the binary was built.


.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-c\fR CONFIG, \fB\-\-config\fR=\fICONFIG\fR
path to the local ksc.conf file. If not specified the tool tries to read from
~/ksc.conf and if that is also not found then from /etc/ksc.conf.
.TP
\fB\-d\fR DIRECTORY, \fB\-\-directory\fR=\fIDIRECTORY\fR
path to the directory with kernel module sources.
.TP
\fB\-i\fR, \fB\-\-internal\fR
to create text files to be used internally.
.TP
\fB\-k\fR KO, \fB\-\-ko\fR=\fIKO\fR
path to the ko file.
You should either  use -d or -k to run the KSC tool, but not both.
If both -d and -k option is used at the same time then only -d is used and the -k option is discarded.
.TP
\fB\-n\fR RELEASENAME, \fB\-\-name\fR=\f\RELEASENAME\fR
Red Hat release against which the bug is to be filed, e.g '6.5'. Default value is 6.5.
.TP
\fB\-p\fR PREVIOUS, \fB\-\-previous\fR=\fIPREVIOUS\fR
path to the previous resultset file and submit it as a bug to Red Hat Bugzilla.
.TP
\fB\-r\fR RELEASE, \fB\-\-release\fR=\fIRELEASE\fR
RHEL whitelist release used for comparison, e.g. '6.5'.
.TP
\fB\-y\fR SYMVERS, \fB\-\-symvers\fR=\fISYMVERS\fR
Path to the Module.symvers file. The current kernel path is used if not specified.
.TP
\fB\-s\fR, \fB\-\-submit\fR
Submits the report to the Red Hat bugzilla (https://bugzilla.redhat.com).
The credentials need to be in the /etc/ksc.conf file. The tool will prompt
for bugzilla password.
.br 
.IP
.B The configuration file looks like below:
.IP
.br 
[bugzilla]
.br 
user=user@redhat.com
.br 
partner=partner\-name
.br 
partnergroup=partner\-group
.br 
server=https://bugzilla.redhat.com/xmlrpc.cgi
.TP
\fB\-v\fR, \fB\-\-version\fR
Prints KSC version number
